# Generated by Django 6.0.6 on 2026-06-30 02:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paqueteturistico',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Paquete Turístico', 'verbose_name_plural': 'Paquetes Turísticos'},
        ),
        migrations.RenameField(
            model_name='paqueteturistico',
            old_name='imagen',
            new_name='imagen_principal',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_viaje',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='cupos_disponibles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='imagen_banner',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes/banners/'),
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(default='QLB-20260629-TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(default='2026-06-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='incluye',
            field=models.TextField(help_text='Lista de servicios incluidos'),
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='no_incluye',
            field=models.TextField(blank=True, help_text='Lista de servicios no incluidos'),
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Requisitos para el tour'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('actividades', models.TextField(help_text='Lista de actividades del día')),
                ('lugar', models.CharField(max_length=200)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='turismo.paqueteturistico')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('codigo_transaccion', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='turismo.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TRANSPORTE', 'Transporte'), ('HOSPEDAJE', 'Hospedaje'), ('ALIMENTACION', 'Alimentación'), ('GUIA', 'Guía Turístico'), ('SEGURO', 'Seguro de Viaje'), ('EQUIPO', 'Equipo Especial'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('paquetes', models.ManyToManyField(blank=True, related_name='servicios_adicionales', to='turismo.paqueteturistico')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
            },
        ),
    ]
